### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pawelgoj** [pawelgoj/pyMayCoor#21]
- [ ] Add app icon
- [ ] Add load data functionality 
- [ ] Add preform calculations functionality 
- [ ] Add save results functionality 
- [ ] Add export results functionality
