### ISSUE TITLE
# TODO

### ISSUE THREAD

**Issue by pawelgoj** [pawelgoj/pyMayCoor#22]
- [ ] Settings fields must change if settings are loaded 
- [ ] Changing widgets state change settings object
- [ ] Add raport viewer 
- [ ] Add information for a user about a performed calculations..
